name: testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug
        
    - name: build
      run: |
        cmake --build build --config Debug
 
    - name: test
      run: |
        cd build
        ctest -C Debug --output-on-failure --verbose
